webui.py
Output tuple was changed, so needs updating.
Also, fix text in the faux 'console box' so it isn't black-on-black with light UI theme.
Oh and I can't stay anon here, so I guess I'll mention that I was the one who made the 'unified' version, that ~~the repo author ((I assume?)~~—er wait no sorry it's in the pull request history—manually ported a bunch of tweaks over from into this fork. Good work, lad.
=> Fix crash display

webui.py
GFPGAN requires images in BGR color space.  Using the wrong color space leads to color-shift of the face after it's put through GFPGAN.  To fix, convert the color channels before sending to GFPGAN and again when it's returned.
=> Fix GFPGAN color errors.

webui.py
`1 in toggles` is right. I'm not an idiot who doesn't know how to read an array index.
For example, the img2img options look like this right now:
```
img2img_toggles = [
'Create prompt matrix (separate multiple prompts using |, and get all combinations of them)',
'Normalize Prompt Weights (ensure sum of weights add up to 1.0)',
'Loopback (use images from previous batch when creating next batch)',
'Save individual images',
'Save grid',
]
```
And if for example we were to tick these in the UI, in this order:
```
'Create prompt matrix (separate multiple prompts using |, and get all combinations of them)',
'Save individual images',
'Loopback (use images from previous batch when creating next batch)',
```
the list sent to img2img's `toggles` var would look like `[0,3,2]`
So to see if that …
=> The same PR I made last time

txt2img.yaml, webui.py
Currently it is not possible to use txt2img as part of a script.
This would be useful to ensure that CLI usage produces the exact same outputs as GUI usage.
This PR implements this functionality.
Usage:
The user can add the --cli command line argument to not launch the server and instead just generate images.
The --cli command line argument takes as input the path of a YAML config file that replaces the manual inputs via the GUI.
An example YAML config file is included.
Since most users presumably prefer a GUI the changes are designed to be as non-intrusive as possible.
The downside is that YAML config files will break if the names of function arguments are changed.
Help wanted:
I do not understand the significance of the argument `fp` that is passed to `txt2img` and `img2img`.
I am …
=> Scripting support for txt2img

webui.py
If loading Arial fails, try loading a font commonly installed on Linux
distros.
This means it continues to work on Windows, and will also just work on
most Linux machines (DejaVu Sans is widely available and often installed
by default).
=> Fix font loading on linux

webui.py
Fixes `UnboundLocalError: local variable 'keep_mask' referenced before assignment` when submitting from crop mode instead of mask mode.
=> fix(): fix error when generating from crop mode

webui.py, webui.yaml
Adds support for configuring UI default values using the same configuration file format used for the `--cli` parameter. By default it looks for the file in `configs/webui/webui.yaml`.  The `target` parameter is currently unused but could be used to select the default tab, however I don't see an option for that in Gradio.
=> Add support for configuring UI defaults

txt2img.yaml, webui.py, webui.yaml
Fixes https://github.com/hlky/stable-diffusion-webui/issues/23 .
Current state of the implementation of separate directories for saving samples.
I have solved the problem of prompt collision by simply logging file names and associated prompts to a text file.
This also helps in cases where people don't remember the full prompt.
I've had an idea for an alternative, however:
You could simply write a YAML file that encapsulates the entire GUI settings for each generated sample.
This would enable people to reliably reconstruct or share the setup for the images they previously generated.
With the script support that I implemented earlier today those YAML files could already be used.
For the GUI it would probably make sense to implement something like a load button (I don't care though). …
=> WIP separate directories

webui.py
Reimplementation of counting png files via glob pattern.
Please confirm that this works with Python < 3.10 ; I don't have a corresponding environment set up.
Also the filenames were getting truncated twice.
I removed on of those.
There should be no functional difference from this.
=> Working glob pattern for counting png files

webui.py
* feature: Add `--gpu` argument for choosing which GPU to use (by index)
* Possibly fixes #67 (haven't tested extensively)
* fix: Make memory monitoring code fail gracefully and prevent causing a divide by zero error with a default of `-1` for the total
* Fixes #75 
* Remove duplicated `MemUsageMonitor` class
=> add '--gpu' argument + memory monitor "fix" for AMD

webui.py
When running the master branch on Linux I get the following error:
```
Traceback (most recent call last):
File "/home/johannesg/Projects/waifu-diffusion/../stable-diffusion-webui/webui.py", line 71, in <module>
os.environ["CUDA_VISIBLE_DEVICES"] = opt.gpu
File "/usr/lib/python3.10/os.py", line 684, in __setitem__
value = self.encodevalue(value)
File "/usr/lib/python3.10/os.py", line 756, in encode
raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int
```
This seems to be because the script is setting an int as an environmental variable.
The problem can be fixed by simply casting the int to str before setting.
I'm assuming this is not an issue on Windows (I have no Windows testing environment set up).
=> Fixed setting environmental variable on Linux

webui.py
Helps prevent out of memory errors when using GFPGAN or ESRGAN. See https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11
Tested working "Fix faces using GFPGAN" and "Upscale images using RealESRGAN" to be run in Text to image on 3060 mobile 6GB.
=> Trigger GC before GAN

webui.py
Max value for a 32bit unsigned int is 2**32 - 1, not 2**32 (and the
range of possible values returned by randint includes both of its
arguments).
Python's hash() function is not deterministic across different
invocations of the interpreter. This meant a given string seed would
produce different results after restarting the script. Use the passed
strings to seed a Random instance instead.
=> Fix seed conversion

webui.py
This should behave much better, for example if (re)moving older files
from the output directories.
Also remove the increments (which never had any effect), and move the
grid_count calculation right before where it's used.
=> Improve sequence number generation

txt2img.yaml, webui.py
This PR does the following things:
1. Fix the example file for CLI usage.
2. Implement specifying YAML files that contain more than one prompt. Prompts are simply processed in order with all parameters being kept the same.
3. Allow users to specify fp via CLI.
4. Only launch server or run headless if the Python interpreter calls `webui.py` directly. This makes it possible to import `wbui.py` from an external Python file and specify arbitrary logic for running the functions in `webui.py`.
5. Unify quotation mark styles.
6. Fix forgotten edit from `seed` to `seeds[i]` (other PR that does this was slightly faster).
=> Basic scripting support, CLI batch processing

webui.py, webui_playground.py
A pretty significant restyling of the complex UI. 
Main things changed: 
✨ Prompt is now large and center, both on txt2img and img2img
✨ Adds the ability (by default) to hit Enter and start generation (if someone needs multiline or for the future multiple prompts, it's supported via simple config) 
✨ Put advanced configs into the advanced tab
✨ Added copy btn to the output seed (TBD adding a copy button to copy the selected image to clipboard)
✨ Moved out the generate buttons to the top fixes #87 
🌐🔒 Added the option to pass --share (with an optional --share-password) so that the UI will be hosted on *.gradio.app which helps use the UI from macs, iphones, ipads etc fixes #96
=> Restyling of the ui

webui.py
Looks like someone else beat me to the Gradio args coincidentally, so I just cut my version.
Added command-line argument:
- --grid-format [png | jpg:quality | webp:quality (lossy) or webp:-compression (lossless)]
- accepts inputs like:
- png (lossless png)
- jpg:80 (lower-quality jpg)
- webp:90 (lossy webp, quality scale 90)
- webp:-100 (lossless webp, max compression)
- also changed default quality from jpg:100 to jpg:95, mostly because the [Pillow documentation](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg) says to use 0-95, and specifically warns against using 100
Wasn't really sure where to put this code, I didn't want to bloat up the UI any more (especially with at least 2 different forks working on overhauling it atm), and some anons were talking …
=> Added --grid-format command-line arg

webui.py
On master unicode characters get dumped as something like `\u4EBA` when writing info files.
This PR sets a flag that dumps the actual unicode characters.
=> Allow unicode in YAML info dicts

webui.py
Include sampler name in image filename to prevent overwriting when same seed is used
=> Prevent overwriting with different sampler

webui.py
Commit 82770bacae08f3b41a0df3eee9fca214d6b7fae6 broke regular prompt
matrix, causing the following error:
Traceback (most recent call last):
File "/.../sd/miniconda3/envs/ldx/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
output = await app.blocks.process_api(
File "/.../sd/miniconda3/envs/ldx/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
predictions, duration = await self.call_function(fn_index, processed_input)
File "/.../sd/miniconda3/envs/ldx/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
prediction = await anyio.to_thread.run_sync(
File "/.../sd/miniconda3/envs/ldx/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File …
=> Fix regular prompt matrix

webui.py
The negative filename reported in #112 was caused by the old (now
replaced) listdir-based sequence number calculation, that incorrectly
subtracted 1 from the number of files already in the directory:
base_count = len([x for x in os.listdir(sample_path_i) if x.endswith(('.png', '.jpg'))]) - 1 # start at 0
The `- 1` was probably copied from the code for the base directory,
which had to subtract 1 to account for the `samples/` subdirectory (that
was before the listdir code started checking file extensions).
The get_next_sequence_number could never return negative numbers, since
it returns `result + 1`, meaning the sequence starts at 0 as intended.
=> Revert bad fix for #112

webui.py
Recent Pullrequest #106 Contains two small changes to the txt2img tab that could easily also be applied to the img2img tab, so I'm transferring those here:
- Sample selection is now a Dropdown
- Seed input is now restricted to one line, which also removes the resize handlebar
Also it added `full_width=True` to several Buttons, but as a parameter for the constructor instead of in `.style()`, which causes a warning in the console.
Added a workaround for a minor visual bug with gradio itself: The output seed box is a number field that is disabled, Gradio will automatically hide the up/down arrows, but only on chromium. On firefox it creates a weird little grey box. I added a new CSS rule that fixes that issue.
=> Minor Fixes to the recent UI restyling

webui.py
The previous color magenta (255, 0, 255) distracts from the actual
images. Use white instead.
The text already has black stroke, so it remains readable even on white
backgrounds.
=> Use white text for alternate text matrix

webui.py
A simple footer with useful links. It's visible on all tabs.
=> Add a simple footer to the bottom of the page

webui.py
Revamped the layout for the output info and actions area.
Indirectly fixes #192
=> Revamped output info area

frontend/css_and_js.py
* Prevent generate button from overlapping prompt text input
* Make multiline prompts match single line prompt styles
=> fix(css): prevent generate button from overlapping prompt

webui.py
modelFS must be removed from GPU memory after each batch is generated, otherwise both modelFS and modelCS will be loaded into memory at once and the script will OOM
=> Fix OOM issue

frontend/frontend.py, webui.py
I ported the variation code over, 
**example workflow** 
Generate some images, 
Pick one and get the seed (this is a manual step, would be nice to just click the image to populate the seed)
**Seed: 4011111492**
In advanced tab, scale up **Variation Amount** slider, the larger the value the more change (keep Variant Seed empty), 
**Variation Amount: 0.1**
click generate
Now you have variations on a seed...  keep clicking generate to get more variations
If you want to mix between 2 seeds, set the **Variant Seed** and use the **Variation Amount** slider as a mixer between 2 seeds
**Recalling past variants**
This is where it is a little tricky, since Variants are made by 2 sets of noise, one generated from Seed and the other from Variant Seed.. there is no way to have a "unified seed" 
So to …
=> Variations

frontend/frontend.py, frontend/ui_functions.py, webui.py
- Almost inpainting-like behaviour
- Works best with small erased areas using "Regenerate masked area"
- Denoiser strength to 1 results to completely in-paint with no previous image info
- Uncrop kind of sometimes works, but not really (use with Denoiser strength 1)
- Works with k-diff samplers & DDIM, but...
- DDIM changes depend on a PR in stable-diffusion core (https://github.com/hlky/stable-diffusion/pull/127)
Still a victim of the weird gradio masking editor bugs
Silly demo
=> Implement masking during sampling to improve blending

frontend/css/no_progress_bar.css, frontend/css/styles.css, frontend/css_and_js.py, frontend/frontend.py, frontend/js/index.js, frontend/ui_functions.py
This is a large change that concerns `frontend` folder.
In short `css_and_js.py` was refactored to be a facade for frontend files which are stored in their respective folders: `css` and `js`.
Currently the implementation is very simple. It bundles together css files based on ops and js is just one big file that exposes SD object to the global space. At a later date it can be expanded as needed while maintaining a simple interface with python scripts via `css_and_js.py`.
I tested it to my ability but the changes are vast so I might have missed a few things.
**IMPORTANT NOTES**
1. To load the js on load event I currently use a hack with invisible element. This is only temporary until the next gradio version is released. My PR has already been merged into master there: gradio-app/gradio#2108 …
=> refactor: decouple python from js and css

webui.py
Prevent model from being loaded into VRAM at startup in optimized mode (causes OOM)
=> Startup OOM fix (optimized)

frontend/css/styles.css, frontend/frontend.py, frontend/ui_functions.py
A number of smaller changes to the img2img tab to be more consistent with the txt2img tab:
- Moved related options to be next to each other. Editor related options are now all right below the editor. the "Editor hints" help text is hidden on a seperate tab rather than the slightly hacky expandable that was there before
- moved other options to be consistent with their positions on txt2img tab
Before/After comparison:
=> img2img tab layout update

webui.py
* Replaced almost all of the code in `split_weighted_subprompts` with a single regular expression
* Moved weight normalization code into the function as an argument
* Functionally, it is almost exactly the same as before. I think the regex pattern is a little better at parsing weights in some edge-case scenarios.
With the regex, all of these formats should either still remaining working, or now work:
* `foo:2` integers
* `foo:-1.23` decimals and negative numbers
* `foo:` no weight (defaults to `1`)
* `foo::123` midjourney-style double-colon syntax (it honestly might be nice to enforce this syntax instead, to enable `:` as a character in prompt tokens? :zipper_mouth_face: )
* `foo:2bar:1` `foo:bar` missing space characters between subprompts? no problem
* `foo:2 bar:1` spaces are fine too …
=> feat: simplify prompt weight splitting function

webui.py
- fixed out of range for simple templating and original templating
- fixed out of range error in image_grid (and before)
- fixed captions for simple templating grid BUT
all these errors were due to differences in len(output_images) and len(prompt_matrix_parts) because the additional data (GFPGAN/RealESRGAN images) was added to the output_images but not in prompt_matrix_parts. thas why i was added new array (for now only to simple templating)
* I recommend adding additional checkboxes or combobox (something like `no grid|simple grid|original grid` - *you name it) it would be great
=> FIx simple tmpl image grid. Detach from orig grid

frontend/css_and_js.py, frontend/frontend.py, frontend/js/index.js
Following the discussion in #313 there is indeed a bug in [submit event](https://github.com/hlky/stable-diffusion/blob/2cb47b6a2ca64c08d1e0b6734a234cc57f37b23c/frontend/frontend.py#L290). It only assumes that the img2img is in Crop mode so it fails in Mask mode.
The way to fix this would be to check which mode is on but **there  is already another mode button in there** so instead I opted out to a simple js fix.
The code finds the first active generate button and clicks it just like a human would. Nice and easy.
=> bugfix: on submit prompt event in img2img

frontend/js/index.js
* Prevent multiple script tags from being loaded if the `Advanced Editor` button is pressed rapidly before painterro has been loaded
* Prevent styles from being applied more than once
* Handle painterro script loading errors more gracefully
* Remove the script tag after an error occurs to allow re-attempts
* Log the error event instead of `false`
* (maybe painterro should be served by the webui directly instead to avoid this scenario and improve the offline experience?)
=> fix: minor painterro integration fixes

webui.py
Currently YAML info file have a relatively low maximum width which introduces line breaks in long prompts.
Since this is annoying for copy-pasting this PR sets the maximum line width to 10000 characters.
=> Set YAML dump width to 10000

frontend/frontend.py, frontend/ui_functions.py
Added a text box to show the **aspect ratio** and the **total pixel count** for the input dimensions for txt2img and img2img.
The total pixel count could be helpful to keep within your VRAM limit and prevent "out of memory" errors.
I'll attach a preview of the UI.
If you have any improvements, please go ahead and let me know.
=> Add dimensions info (aspect ratio and pixel count)

webui.py
* Add a guard against subprompt weights adding up to zero, which can happen when using negative weights
* Add support for escaping colon characters with a backslash
* When escaped, actual colon characters are inserted into prompt tokens 
* `foo\:bar` -> `foo:bar` unsplit
=> fix: add guard against subprompt weights adding up to zero + colon escaping support

webui.py
currently with optimized mode the modelFS gets moved back to CPU inside the for loop thats processing each sample and will endless loop if batchsize > 1 in the 2nd iteration in the time.sleep(1) part since the mem wont go down anymore from the move.
Should be outside and only be moved back once.
=> fix endless sleep with optimized and batchsize

frontend/css_and_js.py, frontend/frontend.py, frontend/js/index.js
Some changes to the `frontend` folder following the feedback in #343.
`css_and_js.py` has been cleaned up. There is only one helper method `call_SD` that will call any method in js SD object you specify. Additionally it will pass any arguments into the method via object so the names of python arguments are translated to js directly.
* Reliance on a shared property has been removed; every method now gets Gradio input argument as `params.x`.
* Methods are allowed to return nullish values now (although those are converted to empty arrays internally for compatibility with Gradio frontend code).
=> refactor: python js interface

frontend/frontend.py, webui.py
Hi
UI:
Here's a refactoring of the way the project handles upscaling, changes:
-Removal of Fix Faces and Upscale options from the generating interface (commented out currently in case we want to keep it)
-Addition of a new tab called Image Lab
-Addition of Single image and Batch processors 
-Cleaner Reimplementation of GoBig 
-Addition of Latent Diffusion Super Resolution upscaler
-Multiple processors in the same run
-Provides a location and base to add more processors like Animation generation or addition of future upscalers.
Future additions:
-Copy generation settings from generation interface to the goBig upscale settings for convenience (not big on JS, will take some time unless someone wants to tackle it)
-Batch process GoBig settings extractor from current file, using metadata or …
=> [Feature] Image Processing tab

frontend/frontend.py, frontend/ui_functions.py
I implemented YAML info files for samples.
Subsequently someone else implemented YAML config files.
However, currently there seems to be no way to load these when using the GUI.
The goal of this PR is to implement this feature.
Detailed goals:
1. Users can restore the default settings without restarting the program.
2. Users can open a file dialog to open a YAML file that specifies settings and load these into the program.
3. Optional: users can automatically read in settings from their OS's clipboard.
4. Optional: users can create more than one config file and switch between them.
I would like feedback regarding the following points:
1. How important do you judge goals 3 and 4 to be?
2. Goal 3 would require the addition of a third party package since Python does not seem to natively …
=> Load YAML settings into GUI

webui.py
This is my first pull request be gentle I made changes so instead of having a file with prompt info for each sample you can just have one file with the prompt info for all files I also made sure the prompts would work with params in prompts
=> Added abilty to log prompts and info to one file instead of several

relauncher.py, webui.py
Changed `relauncher.py` to have easier to set argument parameters for users to change. No longer is editing the main `os.system`  string needed. Now, users can choose to set some of the commonly used arguments (totally open to more additions here) to be True or False, with an added area for users to enter their own custom arguments as desired.
This really should make it easier for users to toggle what parameters they wish to launch with, and prevents them from needing to edit the main launch string for the `webui.py` file.
Addition changes to `relauncher.py` include increasing the relaunch time from 0.5 seconds to 1 second, to allow for easier program closing from the Terminal.
Changed `webui.py` to now include an  `--inbrowser` argument to open the interface automatically in a user's …
=> Changed relauncher.py to have easier to set arguments for users, added --inbrowser as an argument choice

webui.py
Fixes #480 
For some reason, the code that adds an image to output_images—which goes back out to the web UI, and into the function that creates a grid if that's enabled—was conditionalized to _only_ run when `not skip_save`, i.e. when "Save individual images" is ticked.
Not sure if there was some reason for this at some point, or if someone just got the indentation level confused.
=> Fix some things breaking when "Save individual images" is unticked

frontend/frontend.py, frontend/ui_functions.py, webui.py
This adds a text box to Image Lab that displays the metadata
of any PNG files dropped on it. Can be used to read the info
saved with --save-metadata
=> Image Lab: Display Png metadata

README.md, sync_local.py
Add helper script for local development to replicate the github sync action. the script the script sync_local.py reads in sync.yaml file and copies all the files in that list to a destination specified by cmd line args.
Also added section to README for "development Info" with some tips + basic usage of the helper script.
This addresses some of the questions in #263 that I also had.
=> helper script to replicate github sync action

webui.py
I played a lot with variants and wanted to keep track of them by
extending the filename with the variant amount and variant seed.
While doing that, I found that currently, if you give a variant seed and
an image seed and generate more than one image, you end up with the
same image for all runs.
I used increasing variants with the same variant seed for creating
movies that show how a variant is increasingly deviating. I think
those are fascinating and added functionality to WebGUI.
If you now set a seed for the image and the variant and generate more
than one image, it will increase the variant amount by the initial
amount every step. So you can easily make a series of growing variants
and have them fully reproducible.
Here an example of the result:
I hope I made sense :)
=> Enhanced support for variants

frontend/job_manager.py, webui.py
Prints the true callstack of an exception, so that all errors don't seem to be from jobmanager
=> JobManager: Print true exception callstack

frontend/frontend.py, frontend/ui_functions.py, webui.py, webui_playground.py
**Needs scikit-image to work, update environment.yaml in the main repo**
Images are color corrected before being fed back to the loop.
The original implementation by @pyr-000
Should close #457 if merged with master
=> Add color correction on loopback for img2img (add new dependency)

scripts/webui.py
Currently the sampler name is not one of the settings written to the file's metadata when --save-metadata is used. This feels like an oversight given how much the sampler can affect the image, particularly if one of the _a samplers are used.
This PR simply adds it to the metadata.
=> Add sampler name to metadata

frontend/frontend.py, frontend/ui_functions.py, webui.py
Implement feature from #306
I don't know if the proposed external mask solution is acceptable, so I am waiting for reviews.
Change/Fix
* Fix for last gradio update, #577
* Add external mask
* Restored "resize and fill" and "crop and resize"
=> External mask

webui.py
Change wording of save individual files toggle from `skip_save` to `save_each`. Simplifies boolean logic when trying to work through the code
=> refactor skip_save to save_each

frontend/job_manager.py, webui.py
Adds buttons to the JobManager dialog to view the actively iterating image batch, or to skip the actively generating image batch and continue with the rest of the batches
=> JobManager: View and skip active iteration

.gitignore
there is a new folder at the root/gfpgan generated and downloaded by gfpgan after Image Lab face fix and upscale has been performed
=> add gfpgan folder to gitignore, auto gen by imglab

frontend/css/streamlit.main.css, scripts/webui_streamlit.py
Separate CSS into a separate files in frontend/css/streamlit.main.css for easier maintenance.
There is an optional feature to load external css, which might require an async function edit in the future. 
For now everything tested working.
=> (Streamlit) Feature: separate css to external file

scripts/webui_streamlit.py
This is just a quick fix for the just-merged change to make sure we actually read from the correct path.
=> Fixed the user config path in webui_streamlit.py

scripts/webui_streamlit.py
This is a very simple change to add the stats and info to the success message, matching Gradio behavior (although without the fancy formatting) which is useful for, among other things, copying the seed from the last generated image.
=> Output stats

webui-streamlit.cmd, webui.cmd
Fixing bugs introduce in #860, due to trailing whitespace. Urgent since it is breaking changes
=> Urgent fix to remove whitespace in conda env name

ldm/modules/attention.py
Makes the generation use alot less ram at no cost to speed 
on a 3070
Base non optimized current code
768x512 is max res crashes at 832x512
With optimized-turbo SD without this change
can generate max 1024x576
With this change on non optimized SD
can generate 1280x1024 maybe even more
=> Added Attention.py from Optimized SD

frontend/frontend.py
Displays the current device info at the bottom of the page.
For users who run multiple instances of `sd-webui` on the same system (for multiple GPUs), it helps to know which of the active `CUDA_VISIBLE_DEVICES` is being used.
=> frontend: display current device info

frontend/frontend.py
This is a fix for the aspect ratio box being broken (on master and dev). The sliders should cause the aspect ratio info to fill in, but doesn't for txt2img.
The old issue got closed, so I decided to look for a fix and noticed the code was just commented out.
https://github.com/sd-webui/stable-diffusion/issues/219
=> Bugfix for old repo issue 219 -- txt2img aspect ratio box doesn't update

frontend/image_metadata.py, scripts/webui.py
This commit, when combined with Gradio 3.2.1b1+, maintains image metadata as an image is passed throughout the UI. For example, if you generate an image, send it to Image Lab, upscale it, fix faces, and then drag the resulting image back in to Image Lab, it will still remember the image generation parameters.
When the image is saved, the metadata will be stripped from it if save-metadata is not enabled. If the image is saved by *dragging* out of the UI on to the filesystem it may maintain its metadata.
Note: I have ran into UI responsiveness issues with upgrading Gradio. Seems there may be some Gradio queue management issues. *Without* the gradio update this commit will maintain current functionality, but will not keep meetadata when dragging an image between UI components.
=> Metadata cleanup - Maintain metadata within UI

scripts/webui.py
Make the filenames format configurable with a "--filename_format" argument.
All parameters vary depending on our needs and experiments. Some people play a lot with steps, others with CFG, or image dimensions. And it is very handy to have this information in the filenames. Personally, I have to manually change webui.py every time I update the repo, to fit my needs. The best way to make everyone happy is to make the filenames format configurable with a "--name_format" argument. Using tags is the most flexible and scalable way. Something like:
`--filename_format [STEPS]_[CFG]_[SEED]_[PROMPT]`
The supported tags in the name format are: [STEPS], [CFG], [PROMPT], [PROMPT_SPACES], [WIDTH], [HEIGHT], [SAMPLER], [VARIANT_AMOUNT] and [SEED]. If no format is provided as an argument, it will use the …
=> Add filename formatting argument

scripts/relauncher.py, scripts/webui.py
I added a --tiling parameter which patches all models to use padding_mode='circular'. This causes SD to generate tiling images natively, in one go, without extra processing.
More images here https://www.reddit.com/r/StableDiffusion/comments/x5q7no/native_seamless_tile_generation_no_inpainting/
It's a parameter because it requires the models to be reinitialized (as far as I know) so you need to restart anyways. The UI could be modified to reinitialize the model on demand. That would be a desperate PR and it could include the --optimized flag etc.
Code modified from https://gitlab.com/-/snippets/2395088
=> Tiling parameter

README.md
For issue [#884 ](https://github.com/sd-webui/stable-diffusion-webui/issues/884#issuecomment-1242212448), it is highlighted that we need to ensure webui.cmd is run before manually init src, which user might do when downloading the model.
The wiki Installation is clear on the step but current Readme is not explicit enough on this.
Please also add a new line 89 to the Installation.md in [wiki](https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation#optional-additional-models).
Please ensure that you run `webui.cmd` OR `webui_streamlit.cmd` **first** before downloading and initializing `/stable-diffusion-webui/src` folder. Known issues for the installation to be stuck if `src` is manually initiated.
=> For issue :884, ensure webui.cmd before init src

frontend/frontend.py, frontend/ui_functions.py, scripts/webui.py, scripts/webui_streamlit.py
Add mask_restore option to give users the option to restore images based on mask, fixing #665.
Before commit c73fdd78  (Implement masking during sampling to improve blending, #308) image mask was applied after sampling, resulting in masked parts that are not regenerated to actually stay the same.
Since c73fdd78 the masked img2img will change the whole image, even in masked areas. It gives better looking results at first glance, but will result in image degredation when applied a few times. See issue #665.
In the workflow of using repeated masked img2img, users may want to use this options to keep the parts of image they actually want to keep without image degradation. A final masked img2img or whole image img2img with mask_restore disabled will give the better blending of "Implement …
=> Add mask_restore to restore images based on mask, fixing #665

frontend/css/streamlit.main.css
@ZeroCool940711 requested some CSS to center the image on the txt2img tab.
This PR fixes it using `justify-content: center;` added to the appropriate class in the streamlit CSS file.
=> Added CSS to center the image in the txt2img interface

scripts/webui.py
Color correction is already used for loopback to prevent color drift with the first image as correction target #698 . 
The new toggle allows to use the color correction even without loopback mode. 
It helps keeping the colors similar to the input image, useful when refactoring parts of images.
=> Add color correction toggle for img2img

scripts/webui.py
This PR is based on https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/124 by @fuzzytent, which is a feature I've found very useful. The Gradio sketch tool leaves a lot to be desired.
I'll quote fuzzytent's notes about the code:
> If you add an image with an alpha channel to img2img, it is also used for masking. This lets you do the masking with a proper image editor instead of the terrible Gradio one.
> Any pixel with any transparency is treated as part of the mask, so partial transparency doesn't create a partial mask. But it is useful for editors that do not save color information in completely transparent areas.
> If you use both an alpha channel and the Gradio mask they are combined.
I'll also add an important note, which is that the level of transparency affects how …
=> Image transparency can be used as mask for inpainting

configs/webui/webui_streamlit.yaml
Changed `update_preview_frequency` from every 1 step to every 5 steps. This results in a massive gain in performance (roughly going from 2-3 times slower to only 10-15% slower) while still showing good image generation output.
Changed default GFPGAN and realESRGAN settings to be off by default. That way, users can decide if they want to use them on, and what images they wish to do so.
=> Changed Streamit yaml default configs

frontend/frontend.py, scripts/webui.py
Larger batches reduce inference time per image, at cost of VRAM, as explained in [the optimized SD repo](https://github.com/basujindal/stable-diffusion#--n_samples).
On my machine (3060 ti, 8gb VRAM), this lets me run a batch of 50 images at once with 20 steps of DDIM under 4 minutes, with VRAM to spare. Non-optimized with smaller batches would take much longer.
This PR fixes an issue where diffusion completes successfully, but decoding runs out of memory due to batching. Instead, we decode each image by itself. The logic was picked up from the optimized SD code base.
As such, the "images per batch" slider is moved to a more prominent location, and accepts more values.
=> Better support for large batches in optimized mode

scripts/webui.py
Perform masked image restoration for GFPGAN, RealESRGAN, fixing #947
Also fixes bug in image display when using masked image restoration with RealESRGAN.
When the image is upscaled using RealESRGAN the image restoration can not use the original image because it has wrong resolution. In this case the image restoration will restore the non-regenerated parts of the image with an RealESRGAN upscaled version of the original input image.
Modifications from GFPGAN or color correction in (un)masked parts are restored to the original image by mask blending.
=> Perform masked image restoration for GFPGAN, RealESRGAN, fixing #947

scripts/webui.py
check if we're using a scoped-down GPU environment (pynvml does not listen to CUDA_VISIBLE_DEVICES) so that we can measure memory on the correct GPU
=> webui: detect scoped-down GPU environment

frontend/frontend.py
Credit to @[akx](https://github.com/akx) [PR](https://github.com/sd-webui/stable-diffusion-webui/pull/663/commits/e54a1668c986f3b84a67095a1e051e84a5e66e00) which was unfortunately un-merged during migration from hlky to sd-webui. I don't know how to perform git cherry pick from another repo and branch unfortunately so resubmitting a new PR here.
Reference documentation to confirm gr.File no longer has `source` is [here](https://gradio.app/docs/#file).
This remove the following error warning when starting the project.
`\.conda\envs\ldm\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}`
What it looks like now.
=> remove deprecated kwargs/parameter

scripts/webui_streamlit.py
Hi this commit saves the prompt metadata from the previously posted pngdata to the other output file types as Exif "UserComment" json
=> New metadata for other image types

entrypoint.sh
Also set `PIP_EXISTS_ACTION=w` env variable for conda to avoid interaction during setup
=> Docker - Set PYTHONPATH to parent directory to avoid `No module named frontend` error

scripts/webui.py
Checkboxes for the 2 options were being concatenated into one without this comma
=> Add missing comma for nsfw toggle in img2img

entrypoint.sh
This is to ensure consistency in structure across users, if they had previously set VALIDATE_MODELS=false they would possibly not be using symlinks to model_cache
=> Docker validate model files if not a symlink in case user has VALIDATE_MODELS=false set

webui-streamlit.cmd, webui.cmd
This allows it to be run from other directories (or from a launcher that can't customize working directories)
=> Use the webui script directories as PWD

scripts/webui.py
e.g. "shopping mall ### people" will try to generate an image of a mall without people in it. This is a powerful way to finetune images to avoid certain things in ways that are difficult to achieve with prompt weighting alone.
`###` was chosen as a separator to easy to type and be very unlikely to be accidentally included in a prompt.
prompt: `a mall in america, 35mm film`:
prompt: `a mall in america, 35mm film ### people, crowd`
see also #999
=> support negative prompts separated by ###

configs/webui/webui_streamlit.yaml, scripts/Settings.py, scripts/webui_streamlit.py
- Added the Update Image Preview option to be part of the current tab options under Preview Settings.
- Added Dynamic Preview Frequency option for the txt2vid tab which tries to find the lowest value for update_preview_frequency at which we can update the preview image during generation while at the same time minimizing the impact it has in performance.
- Added option to save a video file to the outputs/txt2vid-samples folder after the generation is complete similar to how the save_grid option works on other tabs.
- Added a video preview which shows a video on the txt2vid tab when the generation is completed.
- Formatted some lines of code to make it use less space and fit on a single screen.
- Added a script called Settings.py to the script folder in which Settings for the Setting page …
=> Multiple Improvements to the txt2vid tab and other misc stuff.

scripts/find_noise_for_image.py, scripts/webui_streamlit.py
- Fixed normalization for image2noise (I'm calling it that now)
- Added option for combined image2noise and FFT matched noise
- Fix some issues with masking. You can now interchangeably use black or transparency in your mask texture. Allows both RGB masks and RGBA masks.
=> img2img mask fixes and fix image2noise normalization

.gitignore, webui-streamlit.cmd, webui.cmd
- Allow reading environment.yaml file in either LF or CRLF (#920)
- Only update environment if environment.yaml changes
- Remove custom_conda_path to discourage changing source file
- Fix unable to launch webui due to frontend module missing (#605)
=> launcher: Fix batch file (#920, #605)

frontend/job_manager.py
Typo fix in job manager which could cause max-jobs=1 to stop responding
Closes: #858 #1041
=> Job manager typo fix

frontend/frontend.py, frontend/job_manager.py
Have JobManager buttons skip Gradio's queue, since otherwise they aren't sending JobManager button presses.
Versions of gradio past 3.1.6  (and perhaps even 3.1.6 for some people?) have issues with JobManager not responding to button presses because Gradio won't tell JobManager about them until the queue is empty.
This commit just tells all of the job-manager related buttons to skip the queue. This prevents Gradio from queueing up the button presses.
=> JobManager: Buttons skip queue

docker-compose.yml
Install getting stuck on user prompt because installation previously failed, and pip does not know what to do because some packages were cloned already. This defaults the pip exists action to wiping the already existing lib and re-downloading it
```
sd  | Obtaining GFPGAN from git+https://github.com/TencentARC/GFPGAN#egg=GFPGAN (from -r /sd/condaenv.h7qk_3wn.requirements.txt (line 25))
sd  | What to do?  (i)gnore, (w)ipe, (b)ackup 
sd  | failed
sd  | 
sd  | CondaEnvException: Pip failed
```
=> Patch docker conda install pip requirements

scripts/sd_utils.py, scripts/txt2img.py
- Swapped changes from #1136 in txt2img to mirror img2img logic as the commit didn't properly function and referred to txt2vid models
- Made state variables consistent with img2img.
- Fixed a bug in sd_utils where switching models after running would not reload the used model.
- Fixed update_preview_frequency and update_preview using defaults from webui_streamlit.yaml instead of state variables from UI.
~TODO: Does sd_utils 174:177 need to run every time the model is switched or should it be overwritten using load_sd_model? The if/else as written takes a while to execute if changing models between runs.~ 
`config, device, model, modelCS, modelFS = load_sd_model(custom_model)`
It takes a while if using the un-pruned waifu-diffusion regardless of deleting first or just overwriting. Should …
=> txt2img touch up + model switching

update_to_latest.cmd
An attempt to make it easier for the end user to restore any custom changes without opening a second prompt window.
- After stashing any changes and pulling updates, ask user if they wish to pop changes
- If user declines the restore, drop the stash to prevent the case of an ever growing stash pile
Any feedback or changes are welcome! I'm not really up to date on efficient batch scripting.
Currently git stash pop has the --quiet flag, but if having the full output is preferred, that is okay.
=> Prompt user if they wish to restore changes

frontend/frontend.py
Calculate aspect ratio and pixel count the first time the UI is loaded.
None
=> Calculate aspect ratio and pixel count on start

scripts/webui.py
Add the missing argument img_callback similar to how it is done in img2img sample function.
This fixes the currently broken GoBig, which throws an exception.
> TypeError: sample() got an unexpected keyword argument 'img_callback'
Closes: #1183
=> add missing argument to GoBig sample function, fixes #1183

scripts/webui.py
The regex was not accounting properly for prompt weights that didn't begin with a leading number such as .5 or .1 and was instead splitting those off into their own prompt which got everything all screwed up.
For example, the prompt string of "Fruit:1 grapes:-.5" should parse as [('Fruit', 1.0), ('grapes', -.5)]
but was being incorrectly parsed as
[('Fruit', 1.0), ('grapes', 1.0), ('-.5', 1.0)]
This fixes that by making the regex properly catch decimals.
* relevant motivation
* a summary of the change
* which issue is fixed.
* any additional dependencies that are required for this change.
=> Fixed decimal prompt weights without leading digit

scripts/img2img.py
If "only modify regenerated parts of image" is checked, but no mask is given, an invalid access exception is raised due to the null mask. This just adds a guard clause to ensure we have a mask first.
=> Minor fix: Fix error when attempting to restore a mask, but no mask is given

scripts/sd_utils.py
When early terminating, generation_callback gets invoked but st.session_state is empty, resulting in key errors.
When this happens, we can just return early (since we have indicated we don't care about further preview or progress updates!)
=> Fix errors on early termination

scripts/sd_utils.py
This is a collection of several changes to enhance image display:
* When using GFPGAN or RealESRGAN, only the final output will be displayed.
* In batch>1 mode, each final image will be collected into an image grid for display
* The image is constrained to a reasonable size to ensure that batch grids of RealESRGAN'd images don't end up spitting out a massive image that the browser then has to handle.
* Additionally, the progress bar indicator is updated as each image is post-processed.
This was done to address several issues:
1. When using post-processing, the processed image only flashed for a brief moment, then the final original image was re-displayed
2. In batch mode, each image in the batch was briefly flashed, with the last image being the one finally displayed
3. Large image grids …
=> Better handling for final displays of images

scripts/sd_utils.py, scripts/textual_inversion.py, scripts/txt2img.py, scripts/webui_streamlit.py
This is a very basic implementation of the concept library made by cloning the home tab that is not used for now, the idea is to group images by their folder/token and show them as examples of what kind of styles or objects those concepts will get you when using them in yours prompts. For now only the images are shown on that tab and in no particular order, we can use containers to keep things grouped and then use the caption argument from the image element to show the token on top of it or just write it as title for the container. I will continue to improve this another day.
=> Basic implementation for the Concept Library tab made by cloning the Home tab.

scripts/sd_utils.py
Used loaded_model state variable as an argument for save_sample() calls and added a line to generated txt2img and img2img. Notably useful now that custom models can be switched in the UI. It uses the .ckpt name when custom variables are used, or "Stable Diffusion v1.4" if model.ckpt is.
=> Add .ckpt name to output .yaml files

CONTRIBUTING.md, README.md, _config.yml, docs/1.installation.md, docs/1.linux-installation.md, docs/2.cli.md, docs/3.custom-models.md, docs/4.upscalers.md
Moving the docs back to the repo and deprecating wiki so people can contribute to documentation and keep it up to date with the incoming changes.
Set up to be used as a jekyll static website (so will need to be mirrored to `master` as well).
=> chore: move documentation back to the repo

ldm/modules/attention.py
Move the scale multiplication out of the for loop to improve inference speed. Some standard tests:
| Settings   | Batch Size | Dev                                           | Pull Request                                  |
|------------|------------|-----------------------------------------------|-----------------------------------------------|
| Euler/20   | 10         | (5.51s per image) Peak memory usage: 9657 MiB | (5.59s per image) Peak memory usage: 9600 MiB |
| Euler_a/35 | 10         | (9.45s per image) Peak memory usage: 9577 MiB | (8.51s per image) Peak memory usage: 9646 MiB |
| LMS/50     | 15         | (12.6s per image) Peak memory usage: 8987 MiB | (11.5s per image) Peak memory usage: 8998 MiB |
The change is mainly beneficial to higher batch sizes (and I imagine higher …
=> feat: move scale multiplication in attention.py

.env_docker.example, README_Docker.md, build_docker.sh, docker-compose.yml
* In an effort to streamline the quick-start experience for docker users, I'm proposing a few changes to the docker files.
1. Allow Docker Compose to handle building the image during setup
2. Add a Healthcheck to Docker Compose to make it easier to tell if a container should be reachable during startup
3. Readme modifications supporting these two changes, as well as some innocent rewordings and formatting fixes
Closes: #1260
=> Streamline Docker Quickstart Experience

scripts/sd_concept_library.py
The issue was that the pagination logic was under the concept browser, meaning the concepts were rendered before any pagination logic. 
If a user click on "Next" to display the next page, the list of concepts to display on the page were updated, but the component in charge of rendering them would still have the "previous" list of concepts. 
Adding the pagination logic before the rendering component fix this issue as the new concepts to display are calculated before the rendering component.
=> moved pagination logic before the rendering of the component

webui.cmd
Fixed webui.cmd crash when having () in path.
#1276
=> Fixed webui.cmd crash when having () in path. #1276

scripts/webui.py
Made it so that the image grid is sent to the front end when it is generated for a prompt matrix.
Lets the user review the results without needing to dive into the output files manually. Very handy if the webui is being used via a separate machine.
=> Send the image grid to the front end if generated for a prompt matrix

frontend/frontend.py
Fix broken output info in img2img to highlight parameters like in txt2img.
* change gr.Textbox to gr.Highlightedtext like in txt2img
Closes: #1288
=> Fix broken output info in img2img to highlight parameters 

scripts/webui.py
Remove wrong arguments from save_sample call.
Closes: #1258
=> Remove wrong arguments from save_sample call - fixes 1258

scripts/sd_utils.py
Added simple function to allows us to change the title of the app dynamically instead of only doing it once per app. This could be useful for setting the title on specific pages and making it appear on the browser history.
=> Added simple function to allows us to change the title of the app dynamically.

frontend/frontend.py, frontend/js/index.js
refactor js invocation on txt2img and img2img pages
=> fix: copy of output parameters, closes #1299

scripts/img2img.py
There was a safety check where RealESRGAN and loopback were not allowed to be on at the same time to prevent rapidly growing images (I think, at least) which was causing confusion in the UI since there was no indication this wasn't allowed. Using ESRGAN just on the final iteration should be safe, so this commit enables that.
Closes: Discord [bug - realEsrgan on streamlit](https://discord.com/channels/1015278966375973004/1022572769172525158)
=> Fixed Streamlit bug where RealESRGAN seemed broke

webui.sh
Added clarity on where the sd-v1-4.ckpt should be located before the user is to press Enter.
Without the change it seemed like the script had broken as there is just a blank space before the comma.
- [ x] I have changed the base branch to `dev`
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
=> Add clarity for model location in webui script.

.streamlit/config.toml
By default, Streamlit collects usage statistics and telemetry. See [Streamlit Privacy Policy](https://streamlit.io/privacy-policy)
This implementation disables usage statistics collection and applies when running the SD WebGUI via Streamlit from the `sd` directory.
=> Block Streamlit Usage Stats and Telemetry Gathering

environment.yaml
Changed realesrgan dependency to use pip instead of having to clone the repository on the src folder, this should reduce the amount of stuff that is on the src folder and that causes issues when updating.
- [x ] I have changed the base branch to `dev`
- [ x] I have performed a self-review of my own code
=> Changed realesrgan dependency to use pip instead.

.dockerignore, Dockerfile
This will allow the image to be used outside of the repo (such as in a service like runpod, or by a novice user who doesn't want to pull the git repo and instead use `docker run ...`) once we start pushing the images to Docker Hub.
Closes: Nothing, yet. This is a step in the direction of `#installation-packing:Docker` in Discord.
=> Added source to Docker image

Dockerfile, docker-compose.amd.yml, docker-compose.override.yml, docker-compose.yml, docs/3.docker-guide.md, requirements.txt
AMD support can be built by prefixing your compose commands with 
`docker compose -f docker-compose.yml -f docker-compose.amd.yml ...`
or, by setting 
```
export COMPOSE_FILE=docker-compose.yml:docker-compose.amd.yml
```
in your `.profile` or through a tool like `direnv`
Closes: Discord #installation-packing:AMD, at least for Linux hosts
=> Amd gpu docker

requirements.txt
This reverts commit 2d0a4e8e96405ddc856da045e01748bf76071ad5, reversing changes made to 1190d8858cdbd63f968572eeee07657ec76a6574.
=> Revert "Bump numpy from 1.21.5 to 1.22.0"

scripts/Settings.py, scripts/sd_utils.py, scripts/txt2img.py
-Changes wording on Memory Monitor to not alarm users (happened a few times) 
-Adds config settings "use_upscaling" and "upscaling_method" to settings menu, were already in yaml
=> Settings and defaults for upscaling

scripts/Settings.py
hopefully fixes
```
StreamlitAPIException: All numerical arguments must be of the same type. value has int type. min_value has int type. max_value has NoneType type. step has str type.
Traceback:
File "/home/chris/stable2/sd-web/stable-diffusion-webui/scripts/webui_streamlit.py", line 177, in <module>
layout()
File "/home/chris/stable2/sd-web/stable-diffusion-webui/scripts/webui_streamlit.py", line 141, in layout
layout()
File "scripts/txt2img.py", line 267, in layout
st.session_state.sampling_steps = st.number_input("Sampling Steps", value=st.session_state.defaults.txt2img.sampling_steps.value,
```
for some users
Fixes #1456
=> fix type error

horde_bridge.sh, scripts/webui.py, webui.sh
Fixes a small typo of "Bridg" in horde_bridge.sh
Makes webui.sh skip asking for StreamLit/Gradio if --bridge is passed
More detailed error messages if bridgeData.py is missing/malformed (previously it would only say no bridgeData found, which caused confusion when bridgeData did exist but was incorrectly formatted)
=> Skip WebUI prompt if --bridge passed, Detailed error messages if bridgeData.py fails to load

frontend/css/styles.css, frontend/frontend.py, requirements.txt
* update gradio
* fix some glaring styling issues
Note: the server message has changed and now the address `0.0.0.0:7680` is shown by default which might not work in browsers. The server is still accessible through `localhost`/real ip address
=> chore: bump Gradio to 3.4.1

horde_bridge.cmd, webui-streamlit.cmd, webui.cmd
Minor quality of life update.
Recently launching the webui.bat became a bit more annoying, as it always asks about restoring changes, even if I have none, and then it needs another interaction for no reason (pause>nul).
This change makes sure the interaction is only needed when there were changes stashed, and removes the second pause.
Yesterday I double clicked the shortcut to start the Stable Horde worker overnight, and even noticed the "Y/N" prompt, but went to bed not realizing it also does the (pause>nul) after that... No reason to be this intrusive.
Closes: #1532
=> Don't ask about restoring stash if nothing was stashed

configs/webui/webui_streamlit.yaml, requirements.txt, scripts/Settings.py, scripts/sd_utils.py, scripts/txt2vid.py
- Updated diffusers to 0.6.0.
- Renamed `max_frames` to `max_duration_in_seconds` in txt2vid to reflect better what the option is currently doing.
- Moved txt2vid to use diffusers custom `interpolate_stable_diffusion` pipeline instead of `StableDiffusionPipeline`.
- Added safety checker which is disabled by default.
- Added unique 16-17 characters id to videos so they are not overridden when you create multiple videos with the same prompt and seed.
=> Several improvements to txt2vid

Web_based_UI_for_Stable_Diffusion_colab.ipynb
changed:
"!streamlit run scripts/webui_streamlit.py --theme.base dark --server.headless true true 2>&1 | tee -a /content/log.txt"
to:
"!streamlit run scripts/webui_streamlit.py --theme.base dark --server.headless true 2>&1 | tee -a /content/log.txt" 
avoids 'unknown argument error'
=> Fixed typo in last command

.streamlit/config.toml, scripts/Settings.py, webui.cmd, webui.sh
- Add settings on the settings page to customize most streamlit options including the server address, port and headless mode.
- Changed default server address to localhost.
- Removed default hard coded server address from the cmd and sh file as they are now customizable through the Settings page on the streamlit version.
=> Add settings on the settings page to customize most streamlit options including the server address, port and headless mode.

scripts/img2img.py, scripts/sd_utils.py, scripts/txt2img.py, scripts/txt2vid.py
Fixes #1522, #1604, #1453
LDSR changes in 0c03cedeb9131b0b5d6c1dd280c966ae00fca787 don't always set the session_state keys depending on which combination of post processing models are installed.
Resolves errors such as 
`KeyError: 'st.session_state has no key "use_LDSR"`
`KeyError: 'st.session_state has no key "GFPGAN_model"`
sd_utils changes set these values to defaults when available check fails
The other changes prevent errors if LDSR is installed without RealESRGAN eg:
`File "scripts\txt2vid.py", line 1788, in layout
index=upscaling_method_list.index(st.session_state['defaults'].general.upscaling_method))
ValueError: 'RealESRGAN' is not in list`
=> Fixed errors when post-processing models aren't installed

environment.yaml
The recent addition of the `conda-forge` channel to `environment.yaml` causes PyTorch to be installed from that channel, which prevents normal functionality since that version of PyTorch does not support CUDA at all.
This PR limits `conda-forge` to be only used for NodeJS, fixing the PyTorch installation issue.
N/A:
=> Fix Conda environment for correct PyTorch installation

scripts/txt2vid.py
Frame generation is being done in chunks of the number of samples chosen, so when you needed 120 frames but set 200 samples, it would generate 200 frames.
* Added a break to stop frames from generating once total_frames is reached
=> Stop text2vid at total_frames

configs/webui/webui_streamlit.yaml
Added Sygil Diffusion to the list of models available for the txt2vid tab.
=> Changed the stable diffusion 1.5 ckpt url to use the official one as we no longer need to accept the license to download them.

scripts/sd_utils/__init__.py
=> Fixed hydralit, hydralit_components and no_rerun import error again as pre-commit removed their imports for some reason after I fixed it before.

docker-compose.yml
I'm not sure why this `docker-compose.yml` was deleted in the first place. Nearly half of the instructions in the readme for this repo rely on this file being there. 
Essentially, it's just another way to start up the container using `docker compose` . This makes the container much more usable for power users, as they'd be able to configure volumes much easier. Also, instead of having to remember the whole complicated `docker container run --rm -d -p 8501:8501 -e STREAMLIT_SERVER_HEADLESS=true -e "WEBUI_SCRIPT=webui_streamlit.py" -e "VALIDATE_MODELS=false" -v "${PWD}/outputs:/sd/outputs" --gpus all tukirito/sygil-webui:latest` command, it's as simple as running `docker compose start` or `up`, since all of the configs are in the compose file, you wouldn't need anything …
=> Adding back deleted docker-compose.yml

docs/1.Installation/4.docker-guide.md
* relevant motivation
* a summary of the change
* which issue is fixed.
* any additional dependencies that are required for this change.
=> Merge Dev to Master.

scripts/sd_concepts_library_downloader.py
For context, modelId is getting deprecated https://github.com/huggingface/huggingface_hub/issues/2408
=> Use id rather than modelId from Hugging Face
