webui.py

I think I missed a couple of the recent Gradio grid parameters last time, this should be good, been testing it here. Be sure to refresh the localhost also so it rebuilds the UI

Prompt Weighting

---

webui.py

Great work, thanks anon!! :100: :fire:

img2img-mask

---

webui.py

Moved the demo.launch() call to a non-main thread, so we can listen for keyboard interrupts ourselves and kill the process instead of having to put up with Gradio hanging.
This solves the hang-on-ctrl+C issue for me entirely, I don't _think_ there are any side-effects except what you'd get from killing the process with task manager or whatever (e.g. incomplete image saves if you time it right).

Workaround for Gradio server hanging on keyboard interrupt

---

webui.py

Oops, sorry.
It didn't actually affect functionality in practice, just sloppy.

fix missing 'self's

---

webui.py

feat(): force bigger image input box

---

webui.py

feat(): add copy to img2img

---

webui.py

Fixes #49 and adds a note explaining how to fix #52

fix(): fix mask errors when sending

---

webui.py

Adds editor able to paint over images for img2img corrections.

feat(): add advanced editor

---

webui.py

Trust the value of $CUDA_VISIBLE_DEVICES if it is already set and --gpu
is not passed.

Default --gpu to value of $CUDA_VISIBLE_DEVICES if set

---

webui.py

Seed is no longer defined here, and we have to use seeds[i].

Fix seed not found in save_sample()

---

webui.py

Add simple templating to matrix prompt. If "create prompt matrix" options checked, you can use alternative prompt syntax:
@lovely girl in (red|black|white) dress, art by (met mangindaan|alphonse mucha)
sill produce 3*2 prompt variants with same seed:
lovely girl in red dress, art by met mangindaan
lovely girl in black dress, art by met mangindaan
lovely girl in white dress, art by met mangindaan
lovely girl in red dress, art by alphonse mucha
... and so on

Add simple templating

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/--feature-request.md

This adds issue templates for bug and feature requests (as mentioned in #132 )

Update issue templates

---

webui.py

Fixes font loading on linux (again).

Extract font loading into function and use everywhere

---

webui.py

This got lost at some point for seemingly no reason, so restore it.

Use get_next_sequence_number everywhere

---

webui.py

added new toggle and operations to utilize upscaling using SD
added a new tab to upload your own image regardless of prompts

added gobig/txt2hd implementation

---

webui.py

This was another regression caused by
82770bacae08f3b41a0df3eee9fca214d6b7fae6.
Fixes #147. Fixes #148.

Fix duplicates

---

webui.py

steps and strength for txt2img and gobig tab

added gobig configuration sliders

---

webui.py

The current setup ignores the CLI parameters `ckpt` and `config` because the paths are hardcoded.

Respect `ckpt` and `config` CLI parameters

---

webui.py

should fix the img2img crash. also adds --optimized-turbo from the new basujindal 
version
important: the optimizedSD folder needs to be updated for this to work. tested with https://github.com/basujindal/stable-diffusion/tree/c719877cc404e46fb6691b155e0419a75b36b09f

optimized mode fix/update

---

webui.py

- Added matrix prompt detection (just try find `|` symbol). Now prompt matrix checkbox is obsolete. (I didn't remove this option due to backwards compatibility. But this is need to investigate)
- Added batch count support to matrix (to simple template only for now)
- Added (experemental) auto row count in grid matrix generation dependent on prompt

Simple prompt templating upgraded

---

webui.py

Reverts hlky/stable-diffusion-webui#243
oops

Revert "Simple prompt templating upgraded"

---

webui.py

* Add denoising strength setting to...
* Parameter output (fixes #168)
* PngInfo (if `--save-metadata` arg is used)

feat: add denoising strength to parameter output and pnginfo

---

.gitattributes
.gitignore

Following from #246
> If this is about .gitattributes and .gitignore then it should only be those files
OK, no problem. Here's only `.gitattributes` + `.gitignore`. But please update the line endings in scripts and README yourself then.

.gitattributes + .gitignore v2

---

frontend/css_and_js.py

@nderscore raised a fair concern with the code that was merged in #240, so here's a more robust and less hacky version (just read the discussion in #240 that followed the merge)

Better robustness of styling for prompt and submit

---

webui.py

- Simple templating now support batches
For prompt `@(big|small) city lights` and seed 1 it will be create 4 images:
`big city lights` seed = 1,2
`small city lights` seed = 1,2
- Grid image rows = first group variant count

Batch and row support for simple templating

---

frontend/frontend.py

* Improve integration with painterro library
* `Advanced Editor` button now works on initial click (after loading the library)
* `Get Image from Advanced Editor` button removed - the image will populate after clicking save in the editor
* Image editor now closes on save (necessary to support this sort of workflow, the function can only return once)
* If painterro script fails to load because of a network error, it will now `alert()` an error

feat: improve integration with painterro image editor

---

frontend/ui_functions.py

* :facepalm: Fix bug in mask/crop toggle introduced by #289 
* Toggling between Mask and Crop mode should now hide/show the correct fields
* (This function is very maintainable :upside_down_face: )
* Updated the tips while I was in there.

fix: fix bug in mask toggle

---

webui.py

Bugfix for grid image generator. Fix crash while using simple templating and gfpgan checkbox together.
Need check original grid generator with gfpgan, but i haven't much time for it now.

Simple templating with ESRGAN bug fix

---

frontend/CODEOWNERS

fixes [CHORE] - add codeowners file for altryne on /frontend #386

---

webui_streamlit.py
webui_streamlit.yaml

Here is the initial commit for the streamlit branch with what I have so far made for the version of the WebUI in streamlit, for now it is still basic and the code is probably a mess as I'm just copying things from the main webui.py and slowly adding them to this version, there are a lot of placeholder names like the names of the columns that I created for the layout, they are just col1, col2 and col3, the idea is to use columns, tabs and also expanders to organize the UI so there is not too much stuff shown at once, we also have to make use of the Settings menu  (top right) and the sidebar (on the left) to reduce the amount of stuff on the main UI.

Initial commit for the streamlit version of the WebUI.py

---

webui.py

Batch size slider was removed, stub batch_size arg as 1 for compatibility, 
fixes #463

remove batch_size from img2img

---

webui_streamlit.py

Here is the PR with the changes to the samplers so it would update the image on the UI during the generation, it can probably be done better so if any of you can improve it please do and leave some comments on this discussion #265 so we can share information on how to continue improving this version of the UI.

The image shown on the UI is now updated on every step during generation for the PLMS and DDIM samplers.

---

webui_playground.py

Can't run playground after all the recent changes. This should do it.

update webui_playground, formatting

---

webui_streamlit.py
webui_streamlit.yaml

The image preview for now is affecting performance by more than 50-70% because of the tensor to image conversion which needs improvements, so, if you want to improve performance and don't care too much about the image preview then disable this feature on the sidebar.
I also removed the print statements that were messing up the progress bar making it be on multiple lines instead of just one.

Added option to enable or disable the Image Preview and also to change the frequency in steps at which the image is updated.

---

webui_streamlit.py
webui_streamlit.yaml

Changed the way the image preview is updated on the UI to now use the proper callback from the DDIM and PLMS samplers, for that reason we no longer need to have the code for those samplers inside the webui_streamlit.py file.

Changed the way the image preview is updated on the UI

---

webui_streamlit.py

Fixed the K Diffusion samplers not working as they had different callbacks than the DDIM and PLMS samplers, also removed some unnecessary code that was left over and are no longer needed now that we can use the K diffusion samplers directly.

Fixed the K Diffusion samplers not working as they had different callbacks

---

webui_playground.py

* Small update bringing img2img and text2img to the same style of output, following the feedback by @altryne in #474
* Revert share to False, at some point it was switched to True, not sure if that was intentional but generally speaking we don't want to share playground app.
Sorry I didn't get to push changes in #474 I was asleep when it was merged 😪

Refactor webui_playground.py, set share=False

---

frontend/frontend.py
webui.py

Quick fix to get mask generation back to work. Added mask editor as a separate argument so people stop forgetting it exists.
Closes: #587, Closes: #565, Closes: #564, Closes: #559

fix img2img mask generation

---

frontend/frontend.py
frontend/ui_functions.py
webui_playground.py

* support to move images between crop and mask modes
* introduces weird artifacting on in browser characteristic of Gradio, doesn't affect actual app behavior

update editor_mode.change event handler

---

webui_streamlit.py
webui_streamlit.yaml

- Implemented the basic layout for the Image-to-Image tab on the UI.
- Fixed the condition that checked if the GFPGAN and RealESRGAN models were present on their folders, it was previously checking if the folder existed instead of the model files inside of it.
- Removed the Basic tab from the Text-to-Image tab and changed the Advanced tab to be an expander, the basic tab was not actually been used on the streamlit version of the UI.

Implemented the basic layout for the Image-to-Image tab on the UI.

---

webui_streamlit.py
webui_streamlit.yaml

- Added a progress bar as well as some extra info on top of it to know how the generation is going without having to check the console every time.
- Updated the Image-to-image tab, it is now working at a basic level.
- Disabled RealESRGAN by default for the Image-to-Image tab as it is not working right now.

Added a progress bar and updated the Image-to-image tab.

---

frontend/frontend.py

simplifying img2img_btn_editor.click.
Might create another PR later for full btn.click merge once confirmed

simplify img2img_btn_editor

---

webui.py

Fix for the name conflict i have while syncing the output folder between linux and windows. https://github.com/hlky/stable-diffusion-webui/discussions/599

Fix for name conflict

---

README.md

added link to gradio github for developers to easily find the library to contribute to and extend the web UI

add link to gradio github

---

webui_playground.py

img2img signature was changed in webui -> bringing playground up to speed

Update img2img args indices in webui_playground.py

---

.env_docker.example

docker compose up fails without it

Add .env_docker.example with previous values

---

webui.sh

Sorry to do this, but I seemed to have copied a line I shouldn't have and only noticed it after re-reading the code base.

Remove .bashrc modification from webui.sh

---

scripts/webui_streamlit.py

Added placeholder text "A corgi wearing a top hat as an oil painting.", similar to gradio interface

added placeholder text similar to gradio

---

scripts/webui_streamlit.py

Added convert('RGB) whenever a Image.open() happen to automatically handle 4 channel png files. This is because the model is designed for 3 channel (no alpha) mode.

added auto conversion for 4 channel PNG to RGB

---

frontend/frontend.py
frontend/ui_functions.py

Brings back Crop and its editor
Uncrop is not confirmed to work — disabled for now
Fix indentation and super long lines in webui.py

feat: bring back Crop mode, formatting

---

README.md

Updating the readme file to make correction to the right URL when appropriate, mostly changing:
1. hlky to sd-webui
2. stable-diffusion to stable-diffusion-webui

Update Readme links to sd-webui when appropriate

---

README.md

Co-Authored-By: Hafiidz <3688500+Hafiidz@users.noreply.github.com>

update README with correct URLs

---

configs/webui/webui_streamlit.yaml
scripts/webui_streamlit.py

Added option to set default sampler name from config file, will be useful for those wanting to change the default sampler and have it persist even when closing the UI and opening it again.

Added option to set default sampler name from config file.

---

webui-streamlit.cmd
webui.cmd

Added "git pull" and "git stash" to the cmd scripts so the repo is checked on each launch for updates, this should make it so people who use it can automatically update the code from the repo and be up-to-date without manually using those commands every time.

Added "git pull" and "git stash" to the cmd scripts so the repo is checked on each launch for updates.

---

frontend/css_and_js.py
frontend/frontend.py
frontend/js/index.js

fix: advanced editor works in both editor modes

---

frontend/css_and_js.py
frontend/frontend.py
frontend/js/index.js

refactor js_Call hook to take all gradio arguments

fix: advanced editor (#827), close #811

---

README.md

re-submit under a new branch (previous PR closed by myself before merge)

update readme as per installation step & format

---

README.md
webui-streamlit.cmd
webui.cmd
webui.sh

* automate conda_env_name as per name in yaml
* Embed installation links directly in README.md
Include links to Windows, Linux, and Google Colab installations.
* Fix conda update in webui.sh for pip bug
* Add info about new PRs
Co-authored-by: Hafiidz <3688500+Hafiidz@users.noreply.github.com>
Co-authored-by: Tom Pham <54967380+TomPham97@users.noreply.github.com>
Co-authored-by: GRMrGecko <grmrgecko@gmail.com>

chore: update maintenance scripts and docs  (#891) close #860

---

webui-streamlit.cmd
webui.cmd

Urgent fix to remove whitespace introduced in PR:860

Urgent Fix to PR:860

---

README.md

added steps to contribute to gradio version

add gradio contribution steps

---

README.md

add discord link for gradio-stable-diffusion for supporting developers with gradio questions

add gradio discord link

---

configs/webui/webui_streamlit.yaml
scripts/webui_streamlit.py

The default img2img sampler is indexed at "0", so it could do with an addition of an entry in the config files.

add sampler_name defaults to img2img

---

scripts/webui_streamlit.py

Seems redundant to write 2 not significantly different sets of metadata to the yaml and the file metadata. 
Includes a minor edit to allow webp files to be uploaded to the img2img uploader.

write same metadata to file and yaml

---

environment.yaml
setup.py

Update and sort dependencies. Numpy and opencv has been upgraded because I suspect some underlying dependencies were installing additional versions.
Co-Authored-By: oc013 <101832295+oc013@users.noreply.github.com>
Co-Authored-By: Aarni Koskela <akx@iki.fi>

refactor: sort out dependencies

---

configs/webui/webui_streamlit.yaml
environment.yaml
scripts/webui_streamlit.py

Added some basic layout for the Model Manager tab and added there the models that most people use to make it easy to download instead of having to go to the wiki or searching through discord for links, it also shows the path where you are supposed to put those models for them to work.

Added some basic layout for the Model Manager tab.

---

scripts/webui.py

tell the user which GPU the code is actually going to use before spending lots of time loading everything onto the GPU
also fix a typo

webui: display the GPU in use during startup

---

.dockerignore
.env_docker.example
.gitignore
Dockerfile
docker-compose.yml
docker-reset.sh
entrypoint.sh

Also satisfied some user requested changes from PRs in the old repo:
https://github.com/sd-webui/stable-diffusion/pull/242
https://github.com/sd-webui/stable-diffusion/pull/285

Docker updates - Add LDSR, streamlit, other updates for new repository

---

configs/webui/webui_streamlit.yaml
scripts/webui_streamlit.py

Multiple improvements to the txt2vid tab.
- Improved txt2vid speed by 2 times.
- Added DDIM scheduler.
- Added sliders for beta_start and beta_end to have more control over these parameters on the scheduler.
- Added option to select the scheduler type from scaled_linear or linear.
- Added option to save info files for the txt2vid tab and improved the information saved to include most of the parameters used to run the generation.
- You can now download any model from the huggingface website to use on the txt2vid tab, just add the name to the custom_models_list on the config file.

Multiple improvements to the txt2vid tab

---

scripts/webui.py

show the user what prompt is currently being rendered
useful to check in on a server that may be crashing

webui: add prompt output to console

---

environment.yaml
frontend/css/streamlit.main.css
scripts/webui_streamlit.py
webui-streamlit.cmd

- Added changes made by @Hafiidz to improve the appearance of the sidebar.
- When the sidebar is "Expanded" it will be first minimized to just show the icons on the sidebar and once you hover over it then it will be expanded to show all the content on it.
- By default the cmd file that launches the streamlit WebUI now uses the dark theme for the UI instead of the Light theme, you can always change it back from the Settings Menu on the top right.

Changes made by @Hafiidz to improve the appearance of the sidebar.

---

scripts/find_noise_for_image.py
scripts/matched_noise.py
scripts/webui_streamlit.py

There are still some things to be done before this is "user friendly"
Some settings should only be available for different modes, e.g.
- `Find Noise Steps` should only appear when Noise Mode = Find Noise
- `denoising strength` should be forced to 1.0 when using Find Noise

Add masking to streamlit img2img

---

frontend/frontend.py

* for people who want to use the Gradio API
* added a single parameter to add API Access in the frontends.py for each tab
- [x ] I have changed the base branch to `dev`
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation

add Gradio API endpoint settings

---

scripts/webui_streamlit.py

Loopback currently isn't iteratively processing results but rather is producing them in bulk similarly to having loopback turned off.
I also fixed a bug that prevented `mask_restore` from working unless you turned on ESRGAN - I meant to submit this separately but pushed it to my repo before this was merged.  Whoops.
_**Please note that this does seem to cause color correction and/or "deepfry" issues if you do not use the DDIM sampler**_
Closes: #822

Fix issue where loopback was using batch mode

---

README.md

fix typo
* relevant motivation
* a summary of the change
* which issue is fixed.
* any additional dependencies that are required for this change.

minor spelling error 

---

docker-compose.yml

Publish both ports by default to avoid need for user modification

Publish Streamlit ports

---

docker-compose.yml

(cherry picked from commit 833a91047df999302f699637768741cecee9c37b)

Publish Streamlit ports (#1102)

---

configs/webui/webui_streamlit.yaml
scripts/img2img.py
scripts/sd_utils.py
scripts/txt2img.py

* nvml memory monitor currently can't support multi gpu setup (not related to optimized mode, just `dev` is broken atm)
* only normal mode working for now

fix: add optimized mode to streamlit

---

configs/webui/webui_streamlit.yaml
scripts/img2img.py
scripts/sd_utils.py
scripts/txt2img.py
scripts/txt2vid.py

- Fixed max_frame not being properly used and instead sampling_steps was the variable being use.
- Fixed several issues with wrong variable being used on multiple places.
- Added option to toggle some extra option from the config file for when the model is loading on the txt2vid tab.

Fixed max_frame not being properly used and instead sampling_steps was the variable being use.

---

frontend/job_manager.py
scripts/webui.py

[PR #611 ](https://github.com/sd-webui/stable-diffusion-webui/pull/611) got pretty messed up in the transition to 'dev'. This commit re-merges the feature branch.

Re-merge #611 - View/Cancel in-progress diffusions

---

update_to_latest.cmd
webui-streamlit.cmd
webui.cmd

After my last PR #1106, I've seen some people report errors regarding missing dependencies.
The intent of the last PR was to avoid automatic git commands on startup, but I believe it makes sense to always ensure the dependencies are met.
Thoughts?

Update conda environment on startup always

---

update_to_latest.cmd
webui-streamlit.cmd
webui.cmd

* Update environment on startup always
* Message to explicitly state no environment.yaml update required
Co-authored-by: hlky <106811348+hlky@users.noreply.github.com>

Update conda environment on startup always (#1171)

---

scripts/sd_utils.py

Small change to enable the same negative prompt support on streamlit that gradio has (#1035)

Enable negative prompts on streamlit

---

ldm/modules/attention.py

Taken from https://github.com/Birch-san/stable-diffusion/commit/27e645af1aa45d46ab7a984ed77e9f238efd6fcb which in turn is itself a cherry-pick of https://github.com/lstein/stable-diffusion/pull/540
This I believe will allow to finally incorporate the changes offered in #771
My small rundown in normal mode with the classic k_euler/20 steps:
|                | Dev                                            | Pull Request                                   |
|----------------|------------------------------------------------|------------------------------------------------|
| Batch_size 10  | (6.67s per image) Peak memory usage: 10326 MiB | (5.9s per image) Peak memory usage: 9485 MiB   |
| Batch_count 10 | (8.4s per image) Peak memory usage: 7342 MiB   | (7.5s per image) Peak memory usage: …

feat: optimizations to attention.py

---

scripts/sd_concepts_library_downloader.py
scripts/sd_utils.py
scripts/txt2vid.py

- Improved optimized mode for txt2img, it should be able to generate high resolution images using less VRAM than before.
- Improved txt2vid so it's now possible to generate high resolution images with less VRAM than before.
- Added condition to ensure that the pipe model from txt2vid is removed from memory when switching from the txt2vid tab to txt2img and vice versa.

Improved memory usage for both txt2img and txt2vid.

---

scripts/sd_utils.py

fixes potential division by zero in generation_callback

fix: division by zero, inefficient preview check

---

webui.sh

Added: Automatic downloads for upscaler models
Added: Prompt to ensure users have placed their SD models in the right spot, with automatic handling for placing them.
Changed: Significantly cleaned up `webui.sh` to have a consistent formatting, as well as follow proper Bash conventions. Changed: Compartmentalised the code to be easier to add or change features or functions down the road.
Fixed: Potential issue with conda activation from the script, which was solved by using the `#!/bin/bash -i` shebang.
(I will work on updating the documentation for Linux users next. That will take a bit longer given the nature of how that is handled currently)

Updated `webui.sh` for StreamLit + Enhancements

---

.dockerignore
Dockerfile
README_Docker.md
build_docker.sh
docker-compose.yml
docker-reset.sh
entrypoint.sh
ext_requirements.txt
requirements.txt
sd_requirements.txt
ui_requirements.txt

* Motivation:  Provide a stable Docker-based environment for running/developing the Stable Diffusion WebUI on Linux/Windows WSL2
* The PR revises the Stable Diffusion Dockerfile and eliminates use of Conda package management when using Stable Diffusion WebUI with docker. Python package dependencies have been audited, and are specified with version-pinning in separate `requirements.txt` files corresponding to their relationship to the project. Orphaned packages have been identified and excluded from installation.
* An updated Readme for using Stable Diffusion WebUI via Docker has been included
Closes: # ([820](https://github.com/sd-webui/stable-diffusion-webui/issues/820))

Audit dependencies and revise Docker environment specification

---

webui.sh

Added: More commenting to explain what each part is doing Added: variables to handle the upscaler model URL's to allow for easy changing if needed.
Changed: Order of selection menu to list Streamlit first, since it will be the primary UI going forward.

Improved `webui.sh`

---

docs/2.linux-installation.md

Fixed some issues with the Linux Installation Document.

Improved Linux Docs

---

environment.yaml

Fixed Streamlit >1.12.2 error

---

frontend/css/streamlit.main.css
scripts/sd_concept_library.py

This is a full code rework for the Concept Browser. 
This PR is there to improve the reliability of the concept browser. 
This PR fixes or improves: 
-Better code readeability with and commented code
-Pagination is now working correctly under the concepts cards and the page change will react immediately, no weird behavior due to caching issue/linear flow reading of the variables. 
-Pagination with searches is now working. Previously the pagination was broken when user had a variable in the search input due to not using session state, loosing the query after changing the page. 
-Better layout of the pagination
- Clicking on previous while beeing at page 1 will switch to the last page
- Clicking on next while beeing on the last page will go back to the first page
- Navigating to others part …

better library browser

---

scripts/webui_streamlit.py

- Added basic URL for each page to the address bar for browser history.

Added individual titles on the browser tab for each page.

---

environment.yaml
scripts/sd_concept_library.py
scripts/textual_inversion.py
scripts/txt2img.py
scripts/txt2vid.py

Other changes:
- Removed some unused functions and code so we can upgrade streamlit to version 1.13.0.
- Changed the search bar text_input widget to have a label as its not allowed to be empty on streamlit 1.13.0 and will give a warning and possible an error later.
- Changed some PIL stuff to use resampling to avoid some warnings on the console.

Upgraded the streamlit dependency to version 1.13.0

---

scripts/sd_concept_library.py

This PR handles corrupted images by adding a try-except in the part of the code handling the thumbnail. 
A refresh concept button has also been added so when a user add or remove any concept, a simple clic on the button will refresh the cache and display the new content. 
Closes: #1291, #1313

Concept library improvements

---

scripts/txt2vid.py

Added message on the text to video tab for specifying how to add the huggingface token if its missing.

---

scripts/img2txt.py

Img2txt is working and ready to use but needs more than 8GB of VRAM to work for now. I will be trying to improve that as the next step.

Img2txt is working now 

---

.env_docker.example
Dockerfile
requirements.txt

Docker package sync
Closes: N/A

Img2text docker package updates

---

scripts/sd_utils.py
scripts/txt2img.py

- Added default values to some functions arguments to make them optional.

Fixed GFPGAN upscaling at the end of the generation as well as doing the face restoration.

---

scripts/relauncher.py
webui.sh

This change helps with starting the stable horde bridge, without having to change the relauncher.py every time. It also allows one to start multiple bridges (for multiple GPUs) by passing the `-n` argument to the .cmd/.sh

Allows passing args to webui.sh and webui.cmd

---

scripts/scn2img.py

Intermediate image saving in scn2img tries to save metadata which is not set. This results in warning thrown in console: "Couldn't find metadata on image", originally reported by @codedealer in https://github.com/sd-webui/stable-diffusion-webui/pull/1179#pullrequestreview-1120015859
Metadata for intermediate images is added to fix the warning.
Following metadata is written:
- "prompt" contains the representation of the SceneObject corresponding to the intermediate image
- "seed" contains the seed at the start of the function that generated this intermediate image
- "width" and "height" contain the size of the image.
To get the seed at the start of the render function without using it, a class SeedGenerator is added and used instead of the python generator functions.
Fixes warning thrown …

Add metadata to scn2img intermediate image output

---

docs/1.windows-installation.md

* relevant motivation
* a summary of the change
* which issue is fixed.
* any additional dependencies that are required for this change.
Closes: #1395

fixed missing 'GFPGANv1.4 in doc

---

entrypoint.sh

Add GFPGANv1.4 to the docker download list
Closes: none

Add missing GPFGANv1.4 model to docker list

---

scripts/ModelManager.py
scripts/sd_utils.py
scripts/webui_streamlit.py

- Fixed missing keys on first run, it seems related to server_state doing a rerun in the background on first run which changes the first session_state initialization, this causes it to be empty until the second run.

Added LDSR to model manager.

---

environment.yaml
scripts/sd_utils.py

Changed hydralit and hydralit components order on the environment file as it might be causing some issues.

Fixed error when selecting LDSR without GFPGAN enabled.

---

horde_bridge.cmd
horde_bridge.sh
scripts/webui.py

So that people can start it from the file browser/explorer

Added batch/shell script to explicitly start the stable horde bridge 

---

scripts/ModelManager.py
scripts/img2txt.py
scripts/sd_utils.py
scripts/txt2img.py

- Fixed hard coded separators.
- Walk the directory for GFPGAN so we can also get the older models in case we have more than one, this allow us to compare multiple versions to see how they perform against each other.
- Force model availability, if inside a condition they will only be checked once so in order to see new models you would need to restart streamlit.

Added extra models back to img2txt.

---

daisi_app.py

Changed yaml.load() for yaml.safe_load() in daisi_app.py

---

configs/webui/webui_streamlit.yaml
requirements.txt
scripts/Settings.py
scripts/txt2vid.py

- Fixed GFPGAN not working on txt2vid.

Added the ability to save the video during mid generation when we hit the stop button.

---

configs/webui/webui_streamlit.yaml
requirements.txt
scripts/sd_utils.py
scripts/webui_streamlit.py

- Add option to select between lerp and slerp in txt2vid
- Improved hot reloading for some model options like optimized and float16.

Add option to select between lerp and slerp in txt2vid

---

README.md

- Fix Image Enhancers Documentation link on Readme.md

Fix Image Enhancers Documentation link on Readme.md

---

scripts/hydrus_api/__init__.py
scripts/hydrus_api/utils.py
scripts/img2txt.py
scripts/sd_utils.py
scripts/txt2img.py
scripts/webui_streamlit.py

- Added hydrus_api library which will be used to query hydrus for tags.

Added reraise option for loguru.

---

requirements.txt

LDSR is once again installed to src to be able to import it inside webui
Closes: #1497

revert LDSR installation to be editable

---

data/tags/key_phrases.json
scripts/custom_components/dragable_number_input/__init__.py
scripts/custom_components/dragable_number_input/main.js
scripts/custom_components/key_phrase_suggestions/__init__.py
scripts/custom_components/key_phrase_suggestions/main.css
scripts/custom_components/key_phrase_suggestions/main.js
scripts/custom_components/key_phrase_suggestions/parent.css
scripts/img2img.py
scripts/txt2img.py
scripts/txt2vid.py
scripts/webui_streamlit.py

Added implementation made by @NaMJaG for key phrase suggestions under the prompt.

---

webui.sh

Updated `webui.sh` to work with new v1.5 model files.

Updated webui.sh to work with new v1.5 model files

---

requirements.txt
scripts/txt2vid.py

- Removed stable-diffusion-videos dependency as we no longer need it, it is part of diffusers now as a custom pipeline.
- Changed max frame to max duration in seconds for the stats on txt2vid

Removed stable-diffusion-videos dependency as we no longer need it, it is part of diffusers now as a custom pipeline.

---

Web_based_UI_for_Stable_Diffusion_colab.ipynb
runpod_entrypoint.sh
scripts/APIServer.py
scripts/ModelManager.py
scripts/Settings.py
scripts/diffusers_textual_inversion_2.py
scripts/home.py
scripts/img2img.py
scripts/img2txt.py
scripts/imglab.py
scripts/modeldownload.py
scripts/relauncher.py
scripts/sd_concept_library.py
scripts/sd_concepts_library_downloader.py
scripts/sd_utils.py
scripts/textual_inversion.py
scripts/txt2img.py
scripts/txt2vid.py
scripts/webui.py
scripts/webui_streamlit.py
webui-streamlit.cmd
webui.cmd
webui.sh

Fixed links so they point to the new repo and organization names.

---

scripts/ModelManager.py
scripts/img2txt.py

- Fixed blip model not downloading due to identification issue caused by passing the huggingface token on the url.
- Fixed log not in defaults.

Fixed blip model not downloading due to identification issue caused by passing the huggingface token on the url.

---

webui-streamlit.cmd

- Made sure the cmd script launches the UI even if the model is not present so the user can use the model manager to download them.
- Changed the webui_streamlit.cmd script to use the new model path instead of the old one.

Made sure the cmd script launches the UI even if the model is not present so the user can use the model manager to download them.

---

configs/webui/webui_streamlit.yaml
scripts/img2img.py
scripts/sd_utils.py
scripts/stable_diffusion_pipeline.py
scripts/txt2img.py
scripts/txt2vid.py
scripts/webui_streamlit.py

Added an image editor for img2img, for now its pretty basic and has some bugs but it should do the job better than having to create a mask using an external software and then importing it to the UI every time.

Added basic image editor for the img2img tab.

---

Web_based_UI_for_Stable_Diffusion_colab.ipynb

as above. in case your grandma wants to use it.

Added note at top of colab to remind people to enable a gpu backend.

---

configs/webui/webui_streamlit.yaml
frontend/css/streamlit.main.css
requirements.txt
scripts/barfi_baklavajs.py
scripts/img2txt.py
scripts/post_processing.py
scripts/webui_streamlit.py

- Added a basic implementation of [Barfi](https://github.com/krish-adi/barfi) under the Tools menu which should allow us to create nodes for a node/flow based content generation and potentially allowing us to connect the UI with external apps like Houdini, Blender,etc.
- Added basic post-processing tab which is still being worked on.

Added barfi/baklavajs to the Tools menu and added a new post processing tab which is still a work in progress.

---

webui_flet.py

This PR merges changes made by @aedhcarrick on his fork to improve the code readability on the flet UI and fixes some issues like the prompt box breaking the page title on smaller resolutions, it also rearranges the layout to make better use of the available space. 
Thanks for the changes, really appreciate the help :)

Merging changes made by @aedhcarrick to make the code for the flet UI more readable.

---

scripts/convert_original_stable_diffusion_to_diffusers.py
scripts/txt2vid.py

Fixed the script that convert ckpt models to diffusers not working with some models if they had invalid or broken keys, these keys are now ignored so we can still convert the model.

Fixed bug in txt2vid not allowing you to use custom models.

---

ldm/data/base.py
ldm/data/imagenet.py
ldm/data/lsun.py
ldm/lr_scheduler.py
ldm/models/autoencoder.py
ldm/models/diffusion/classifier.py
ldm/models/diffusion/ddim.py
ldm/models/diffusion/ddpm.py
ldm/models/diffusion/plms.py
ldm/modules/attention.py
ldm/modules/diffusionmodules/model.py
ldm/modules/diffusionmodules/openaimodel.py
ldm/modules/diffusionmodules/util.py
ldm/modules/distributions/distributions.py
ldm/modules/ema.py
ldm/modules/encoders/modules.py
ldm/modules/image_degradation/bsrgan_light.py
ldm/modules/x_transformer.py
ldm/util.py
requirements.txt
scripts/sd_utils/__init__.py

- Fixed issue with new ldm folder requiring the personalization_config to be set even if empty.
- Added shutup as a dependency to shutup python warnings for good.

Using a different ldm folder to help with memory management and allowing users to render bigger resolutions without running out of memory.

---

.gitignore
configs/webui/webui_flet.yaml
scripts/webui_flet.py
scripts/webui_flet_utils.py

More update/changes to flet wedui, still WIP.
added re-orderable layers panel.
added messages to bottom panel.
changed appbar to row.

updates to flet webui

---

webui/flet/scripts/flet_canvas.py
webui/flet/scripts/flet_gallery_window.py
webui/flet/scripts/flet_layer_manager.py
webui/flet/scripts/flet_utils.py
webui/flet/webui_flet.py

continued de-spagettification.
moved gallery window to 'scripts/flet_gallery_window.py'
started storing settings in page then tying control attributes to them.
added 'import base64' and 'from io import BytesIO' to flet_utils.py

more updates to 'webui_flet.py' (WIP)

---

ldm/models/autoencoder.py
ldm/models/diffusion/ddim.py
ldm/models/diffusion/ddpm.py
ldm/models/diffusion/dpm_solver/dpm_solver.py
ldm/models/diffusion/dpm_solver/sampler.py
ldm/models/diffusion/plms.py
ldm/modules/attention.py
ldm/modules/diffusionmodules/model.py
ldm/modules/diffusionmodules/openaimodel.py
ldm/modules/diffusionmodules/util.py
ldm/modules/distributions/distributions.py
ldm/modules/ema.py
ldm/modules/encoders/modules.py
ldm/modules/image_degradation/bsrgan_light.py
ldm/util.py
scripts/sd_utils/__init__.py

You can now just drop your `ckpt` file with the `yaml` next to it on the `models/custom` folder.
Closes: #1686

Added support for loading custom yaml files for the stable diffusion 2.x models. 

---

docs/1.Installation/4.docker-guide.md
scripts/sd_utils/__init__.py

Fixed hydralit, hydralit_components and no_rerun import error again as pre-commit removed their imports for some reason after I fixed it before.

Merge Dev to Master

---

.env_docker.example

Add .env_docker.example with previous values.
